# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'travelscrapbookapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swiftChatter
  pod 'SDWebImage'
  pod 'Alamofire'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'SQLite.swift', '~> 0.14'

end

